name: sample_flutter
description: Sample Flutter app using sqliteraw
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  sqliteraw:
    path: '../../sqliteraw'

dev_dependencies:
  ffi:
    git:
      url: https://github.com/TarasMazepa/dart-lang-native.git
      path: pkgs/ffi
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  ffi:
    git:
      url: https://github.com/TarasMazepa/dart-lang-native.git
      path: pkgs/ffi

flutter:
  uses-material-design: true
