name: sqliteraw
description: SQLite raw Dart ffi, no alterations, so that you can use the full SQLite C API
version: 0.0.1-3530300
repository: https://github.com/TarasMazepa/sqliteraw.dart

environment:
  sdk: ^3.10.0

dependencies:
  code_assets: ^1.2.1
  ffi: ^2.1.4
  hooks: ^2.0.2
  logging: ^1.3.0
  native_toolchain_c: ^0.19.1
  web: ^1.1.1

flutter:
  assets:
    - wasm/out/sqliteraw.wasm

dev_dependencies:
  ffigen: ^17.0.0
  lints: ^5.0.0
  test: ^1.24.0

ffigen:
  output: 'lib/src/native/bindings.dart'
  ffi-native:
    asset-id: 'package:sqliteraw/sqliteraw.dart'
  headers:
    entry-points:
      - '../sqlite/sqlite3.h'
