name: Build SQLite Binaries

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-linux-gnu
            platform_dir: linux-x86_64
            lib_name: sqlite3.so
            exe_name: sqlite3
          - os: windows-latest
            target: x86_64-windows-gnu
            platform_dir: windows-x86_64
            lib_name: sqlite3.dll
            exe_name: sqlite3.exe
          - os: macos-latest
            target: x86_64-macos-none
            platform_dir: macos-x86_64
            lib_name: sqlite3.dylib
            exe_name: sqlite3
          - os: macos-latest
            target: aarch64-macos-none
            platform_dir: macos-aarch64
            lib_name: sqlite3.dylib
            exe_name: sqlite3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.14.1

    - name: Create build directory
      run: mkdir -p build/${{ matrix.platform_dir }}

    - name: Compile SQLite shared library
      run: |
        zig cc -target ${{ matrix.target }} -shared sqlite/sqlite3.c -o build/${{ matrix.platform_dir }}/${{ matrix.lib_name }}

    - name: Compile SQLite shell executable
      run: |
        zig cc -target ${{ matrix.target }} sqlite/sqlite3.c sqlite/shell.c -o build/${{ matrix.platform_dir }}/${{ matrix.exe_name }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.platform_dir }}
        path: build/${{ matrix.platform_dir }}/ 