name: Compile SQLiteRaw Library

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, macos-13, windows-latest ]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    - uses: dart-lang/setup-dart@v1
    - run: dart pub get
      working-directory: ./sqliteraw
    - run: dart compile exe bin/sqliteraw.dart -o sqliteraw
      working-directory: ./sqliteraw
