name: sqlite-build-mac-apple-silicon

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  SQLITE_COMPILE_TIME_OPTIONS: >-
    -O3
    -DSQLITE_ENABLE_FTS4
    -DSQLITE_ENABLE_FTS5
    -DSQLITE_ENABLE_RTREE
    -DSQLITE_ENABLE_GEOPOLY

jobs:
  sqlite-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - run: clang --version

    - run: mkdir -p "build/macos-aarch64"

    - run: |
        # Build shared library
        clang -dynamiclib \
          ${{ env.SQLITE_COMPILE_TIME_OPTIONS }} \
          sqlite/sqlite3.c \
          -lm -lpthread \
          -o "build/macos-aarch64/sqlite3.dylib"
        
        # Build command-line tool
        clang \
          ${{ env.SQLITE_COMPILE_TIME_OPTIONS }} \
          sqlite/sqlite3.c sqlite/shell.c \
          -lm -lpthread \
          -o "build/macos-aarch64/sqlite3"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sqlite-macos-apple-silicon-builds
        path: build/
        retention-days: 7