name: sqlite-build-linux-x86_64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  SQLITE_COMPILE_TIME_OPTIONS: >-
    -O3
    -DSQLITE_ENABLE_FTS4
    -DSQLITE_ENABLE_FTS5
    -DSQLITE_ENABLE_RTREE
    -DSQLITE_ENABLE_GEOPOLY

jobs:
  sqlite-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: |
        sudo apt-get update
        sudo apt-get install -y clang

    - run: mkdir -p "build/linux-x86_64"

    - run: |
        # Build shared library
        clang -fPIC -shared \
          ${{ env.SQLITE_COMPILE_TIME_OPTIONS }} \
          sqlite/sqlite3.c \
          -lpthread -ldl -lm \
          -o "build/linux-x86_64/sqlite3.so"
        
        # Build command-line tool
        clang \
          ${{ env.SQLITE_COMPILE_TIME_OPTIONS }} \
          sqlite/sqlite3.c sqlite/shell.c \
          -lpthread -ldl -lm \
          -o "build/linux-x86_64/sqlite3"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sqlite-linux-x86_64-builds
        path: build/
        retention-days: 7