name: Test Dart Compilation
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dart-sdk: [stable, beta]
    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.dart-sdk }}
      
      - name: Install dependencies
        run: dart pub get
      
      - name: Analyze code
        run: dart analyze --fatal-infos
      
      - name: Run tests
        run: dart test
      
      - name: Test compilation
        run: dart compile exe test/compile_test.dart